### ISSUE TITLE
there is something wrong with btraj

### ISSUE THREAD

**Issue by sunhaoshui** [HKUST-Aerial-Robotics/Btraj#1]
when i am compiling the pkg,it turns out with:
fatal error: sdf_tools/SDF.h: No such file or directory compilation terminated.
what should i do?

**Comment by USTfgaoaa** [comment]
I'm sorry for hearing that. I will check it ASAP.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by USTfgaoaa** [comment]
@sunhaoshui Sorry man, I have only tested the compilation of my code on 2 computers. I'm in ICRA right now and may not be able to resolve the problem immediately. But I promise I will resolve it right after I come back to HK in this Sunday.

**Comment by wang81522472** [comment]
@sunhaoshui Did you check in the devel/include/sdf_tools directory in your workspace? Is there a file called SDF.h in it? If there is no such file, first try to use catkin_make -j1 and see if there is such file generated. If it still does not work, try to compile the sdf_tools package separately and recompile the whole package.

**Comment by sunhaoshui** [comment]
@wang81522472  yes ,files are in devel folders. The compile is done!
