### ISSUE TITLE
Report a BUG in random_forest_sensing.cpp

### ISSUE THREAD

**Issue by tlb9551** [HKUST-Aerial-Robotics/Btraj#12]
Hello~
I found a small bug in random_forest_sensing.cpp  
https://github.com/HKUST-Aerial-Robotics/Btraj/blob/5686dededa1cae7e46d0e3969dd9c6f60837c641/src/random_forest_sensing.cpp#L67
Here _**x,y**_ is added by _0.5 * resolution_, so **_x,y_** should not add _0.5 * resolution_ again in line 77 again.
https://github.com/HKUST-Aerial-Robotics/Btraj/blob/5686dededa1cae7e46d0e3969dd9c6f60837c641/src/random_forest_sensing.cpp#L77 
This will cause the coordinates of the cloud points to be a multiple of _resolution_, due to imprecision of **double** data type, there will be some gaps in the collision map built by the point cloud.
I found this bug when I set the margin coefficient to 0, some paths pass through the middle of the obstacle.

**Comment by USTfgaoaa** [comment]
@tlb9551 Thanks for pointing out this bug.
