### ISSUE TITLE
 Abnormal report error 

### ISSUE THREAD

**Issue by jiejiezhang** [HKUST-Aerial-Robotics/Btraj#13]
Hi 
My test environment:  Ubuntu 18.04, ROS melodic.
 I follow the Btraj readme configuration steps as follows :
　　1. install  armadillo

        2.  sudo apt-get install libarmadillo-dev
            cd ~/catkin_ws/src
            git clone https://github.com/HKUST-Aerial-Robotics/plan_utils.git
           cd ../
           catkin_make
           source ~/catkin_ws/devel/setup.bash

         3. cd ~/catkin_ws/src
             git clone https://github.com/HKUST-Aerial-Robotics/Btraj.git
             cd ../
             catkin_make
             source ~/catkin_ws/devel/setup.bash

           4.   roslaunch bezier_planer simulation.launch

 **It made the following errors,:**
![Screenshot from 2020-07-26 12-15-58](https://user-images.githubusercontent.com/23076781/88475376-c5786300-cf61-11ea-953d-91a653bd9895.png)

Who can help me to see what's reason?

**Comment by USTfgaoaa** [comment]
@jiejiezhang I can't figure out what's the error? Looks like some warning. I think maybe in 18.04 the rviz_tool can't be used.

**Comment by jiejiezhang** [comment]
>   I think maybe in 18.04 the rviz_tool can't be used

Thanks!
