### ISSUE TITLE
Build failed on my own PC

### ISSUE THREAD

**Issue by paulwong16** [HKUST-Aerial-Robotics/Btraj#3]
Hi Gao,

It seems something wrong happened with catkin_make, would you mind helping me fix it?

All the best wishes,

make[2]: *** [Btraj/third_party/sdf_tools/CMakeFiles/sdf_tools.dir/src/sdf_tools/sdf.cpp.o] 错误 1
make[2]: *** 正在等待未完成的任务....
make[2]: *** [Btraj/third_party/sdf_tools/CMakeFiles/sdf_tools.dir/src/sdf_tools/dynamic_spatial_hashed_collision_map.cpp.o] 错误 1
make[2]: *** [Btraj/third_party/sdf_tools/CMakeFiles/sdf_tools.dir/src/sdf_tools/collision_map.cpp.o] 错误 1
make[1]: *** [Btraj/third_party/sdf_tools/CMakeFiles/sdf_tools.dir/all] 错误 2
make: *** [all] 错误 2
Invoking "make -j12 -l12" failed

**Comment by USTfgaoaa** [comment]
@paulwong16 Sure I will check the compilation now. Also I recommend you try to remove the generated files in catkin_ws/devel and catkin_ws/build/ and compile it again.

**Comment by USTfgaoaa** [comment]
@paulwong16 Paul, I can compile this package, maybe I should test it on many other machines. Before that, under what environment (ubuntu version, gcc version) you are compiling?

**Comment by USTfgaoaa** [comment]
@paulwong16 Also, try to use the command catkin_make -j1 instead of catkin_make .

**Comment by paulwong16** [comment]
I have copied the warnings shown in the terminal when compiling in this file.

[warnings.txt](https://github.com/HKUST-Aerial-Robotics/Btraj/files/2097300/warnings.txt)

**Comment by USTfgaoaa** [comment]
@paulwong16 Actually we can not guarantee anything if your environment is 14.04. I will find a 14.04 machine and try it. Will reply you later. But, seemed that there are some problems related to boost library. I don't think I can deal with that and I would suggest you switch to 16.04.

**Comment by paulwong16** [comment]
@USTfgaoaa Thank you, Gao. I will try to build it on another computer running 16.04. In addition, I noticed that the same wrong happened when I compiling the package [GTOP](https://github.com/HKUST-Aerial-Robotics/grad_traj_optimization). I also consider that it was related to boost library, could you tell me which version of boost library that you are using?

**Comment by USTfgaoaa** [comment]
@paulwong16 boost 1.58 I think, along with ros-kinetic.
