### ISSUE TITLE
trouble of catkin_make 

### ISSUE THREAD

**Issue by pp-user** [HKUST-Aerial-Robotics/Btraj#5]
**when I compile the Package Bteaj, error:** 

/usr/bin/ld: skipping incompatible /home/nvidia/catkin_wsu/src/Btraj/third_party/mosek/lib/mosek8_1/libmosek64.so when searching for -lmosek64
/usr/bin/ld: cannot find -lmosek64
/usr/bin/ld: skipping incompatible /home/nvidia/catkin_wsu/src/Btraj/third_party/mosek/lib/mosek8_1/libmosek64.so when searching for -lmosek64
/usr/bin/ld: cannot find -lmosek64
collect2: error: ld returned 1 exit status
Btraj/CMakeFiles/b_traj_node.dir/build.make:579: recipe for target '/home/nvidia/catkin_wsu/devel/lib/bezier_planer/b_traj_node' failed
make[2]: *** [/home/nvidia/catkin_wsu/devel/lib/bezier_planer/b_traj_node] Error 1
CMakeFiles/Makefile2:2672: recipe for target 'Btraj/CMakeFiles/b_traj_node.dir/all' failed
make[1]: *** [Btraj/CMakeFiles/b_traj_node.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j6 -l6" failed

**Comment by pp-user** [comment]
> **when I compile the Package Btraj, error:**
> 
> /usr/bin/ld: skipping incompatible /home/nvidia/catkin_wsu/src/Btraj/third_party/mosek/lib/mosek8_1/libmosek64.so when searching for -lmosek64
> /usr/bin/ld: cannot find -lmosek64
> /usr/bin/ld: skipping incompatible /home/nvidia/catkin_wsu/src/Btraj/third_party/mosek/lib/mosek8_1/libmosek64.so when searching for -lmosek64
> /usr/bin/ld: cannot find -lmosek64
> collect2: error: ld returned 1 exit status
> Btraj/CMakeFiles/b_traj_node.dir/build.make:579: recipe for target '/home/nvidia/catkin_wsu/devel/lib/bezier_planer/b_traj_node' failed
> make[2]: *** [/home/nvidia/catkin_wsu/devel/lib/bezier_planer/b_traj_node] Error 1
> CMakeFiles/Makefile2:2672: recipe for target 'Btraj/CMakeFiles/b_traj_node.dir/all' failed
> make[1]: *** [Btraj/CMakeFiles/b_traj_node.dir/all] Error 2
> Makefile:138: recipe for target 'all' failed
> make: *** [all] Error 2
> Invoking "make -j6 -l6" failed

**Comment by USTfgaoaa** [comment]
@pp-user Hi, in which device you compile the package? I found 'nvidia' in your error code, so are you compiling it in an arm-architecture device (TX1, TX2)? If yes, then you can not link 'Btraj' to 'Mosek', because the convex solver I use, 'Mosek', is compiled in X86-architecture, and it's only compatible with X86-architecture devices.

**Comment by pp-user** [comment]
ok,  Thank you very much for your reply, my device is "TX2", I will try to compile in X86-architecture again. Thanks!
