### ISSUE TITLE
something wrong with catkin-make

### ISSUE THREAD

**Issue by zhouwei342622** [HKUST-Aerial-Robotics/Btraj#7]
Hi Gao,
It seems something wrong with catkin_make,Would you mind helping me fix it ?
thanks a lot.
(I test it on Ubuntu 16.04)

CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "quadrotor_msgs"
  with any of the following names:

    quadrotor_msgsConfig.cmake
    quadrotor_msgs-config.cmake

  Add the installation prefix of "quadrotor_msgs" to CMAKE_PREFIX_PATH or set
  "quadrotor_msgs_DIR" to a directory containing one of the above files.  If
  "quadrotor_msgs" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  Btraj-master/CMakeLists.txt:6 (find_package)

-- Could not find the required component 'quadrotor_msgs'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "quadrotor_msgs"
  with any of the following names:

    quadrotor_msgsConfig.cmake
    quadrotor_msgs-config.cmake

  Add the installation prefix of "quadrotor_msgs" to CMAKE_PREFIX_PATH or set
  "quadrotor_msgs_DIR" to a directory containing one of the above files.  If
  "quadrotor_msgs" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  Btraj-master/CMakeLists.txt:6 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/zhouwei/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/zhouwei/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

**Comment by USTfgaoaa** [comment]
@zhouwei342622 Have you clone and compiled all packages from here: https://github.com/HKUST-Aerial-Robotics/plan_utils 

That repo should contain quadrotor_msgs.

**Comment by zhouwei342622** [comment]
你好，我在windows上下载了上面 提到的两个压缩包，然后解压放在我自己的src工作空间中，我也查询了Cmakelists.txt文件中包含了quadrotor_msgs目录，执行的时候还是有问题。麻烦您看一下，谢谢！

**Comment by USTfgaoaa** [comment]
@zhouwei342622 Try compiling quadrotor_msgs first, then Btraj.

BTW, have you sourced the workspace? source setup.bash in devel folder

**Comment by zhouwei342622** [comment]
谢谢你的回复，不好意思，我是小白，我应该执行怎样的指令来在我的终端中编译quadrotor_msgs?在这个文件夹中是要执行这样的指令吗？$ source setup.bash

**Comment by USTfgaoaa** [comment]
@zhouwei342622 in your_catkin_ws/devel, 
do:  source setup.bash

If you want to compile only one specific package (not all packages in your workspace), use the command:
catkin_make --pkg quadrotor_msgs

**Comment by zhouwei342622** [comment]
thank you very much .I will try it later.

**Comment by USTfgaoaa** [comment]
@zhouwei342622 
1. 没有公开数据集，我们准备近期自己做一个仿真里的数据集。
2. 实验数据是实验同时统计的；benchmark 结果是在仿真里随机地图测试的
3. 没有；是

**Comment by zhouwei342622** [comment]
thank you for your reply
